POST http://localhost:8080/article_like/dislike
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU3MDY0MzMsImV4cCI6MTY1NTkyMjQzMywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIn0.80RFxu4TKfWW9EJmw_E2cgueewz_z8AFFMGDLw6fWE4

{
  "articleId": "ff808081816269b90181627015650000"
}