POST http://localhost:8080/article/adm/create
Content-Type: application/json
#Authorization: Ali alish123

{
  "title": "qweqwe",
  "content": "lllll",
  "description": "kkkkk",
  "regionId": 1,
  "categoryId": 1,
  "typesList": [1, 2],
  "tagList": ["qweqe", "sddss"]
}

###

GET http://localhost:8080/article/list/mod/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMDMxODEsImV4cCI6MTY1NTIwNjc4MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.zaaGSHISWURG89I_61m-C8DUUxF1KmqWOOcWDf83z28

###

GET http://192.168.43.194:8080/article/list

###

GET http://localhost:8080/article/list/type?key=dolzarb


###

DELETE http://localhost:8080/article/delete/4028ab428157bce8018157bdbded0000
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUwNDk4MjgsImV4cCI6MTY1NTA1MzQyOCwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.LJl8zheQTQMAX2T0ediViN27SrROrNpwgdG9lkhNJbk

###

GET localhost:8080/article/pagination?page=1&size=10

###

GET localhost:8080/article/list/8
Content-Type: application/json

{
  "idList": ["8a8a85138167727401816774b5140001",
  "8a8a851381677274018167740d740000",
  "ff808081816269b9018162744c3a000c"]
}

###

GET http://localhost:8080/article/list/3?type=dolzarb


###
GET http://localhost:8080/article/category/dolzarb
###
GET localhost:8080/article/list4_most
###
GET localhost:8080/article/listByTag/meva
###
GET localhost:8080/article/listByTypeByRegion/dolzarb/buxoro
###
PUT localhost:8080/article/adm/view_count
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU2NTQxOTYsImV4cCI6MTY1NTg3MDE5NiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo0LCJyb2xlIjoiVVNFUiJ9.5hRlWaovrLiRMo_fUb7sem8oI--NvU7nCvmayN35Xug
Content-ID: 8a8a85138167727401816774b5140001
###
GET localhost:8080/article/listByCategoryByPagination?category=a&page=0&size=5
###
GET localhost:8080/article/listFullInfo
Accept-Language: uz
Content-ID: ff808081816269b90181627437130008

###
GET localhost:8080/article/public/category/a
