POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "ASD",
  "surname": "zxc",
  "email": "asd123@gmail.com",
  "password": "1234",
  "phone": "123456789123"
}


###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "moder",
  "password": "1234"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "123"
}

###


POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user",
  "password": "123"
}
