POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Moderjon",
  "surname": "MMM",
  "email": "moder1",
  "password": "123"
}


###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "moder",
  "password": "1234"
}