POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "email": "ali",
  "password": "123"
}


###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "123"
}