POST http://localhost:8080/profile/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUzNzc2NjIsImV4cCI6MTY1NTU5MzY2MiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.5NUIbg4ka43w1Q9-QREdhTTdcx4ebLCXDjUyZI6R7rI

{
  "name": "Lazgi",
  "surname": "Lazgiyev",
  "email": "lazgi",
  "password": "1234",
  "role": "user"
}

###

PUT http://localhost:8080/profile/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ3ODY1MTUsImV4cCI6MTY1NDc5MDExNSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjo3LCJyb2xlIjoiVVNFUiJ9.78UycSUGq3AnZ7TtJie4f_S3ya7jxASqwM_NsMScryw

{
  "name": "Valijon",
  "surname": "Valijonov",
  "password": "123"
}


###

GET http://localhost:8080/profile/list/USER
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4MDgyMDYsImV4cCI6MTY1NDgxMTgwNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.T90vwPp01aCpQcqJQKAyjY52e_ns9dFaLB74-xiHBFE


###

DELETE http://localhost:8080/profile/delete/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4MDgyMDYsImV4cCI6MTY1NDgxMTgwNiwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.T90vwPp01aCpQcqJQKAyjY52e_ns9dFaLB74-xiHBFE