POST http://localhost:8080/region/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTUyMTM1MTMsImV4cCI6MTY1NTIxNzExMywiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.g4UibfGApMButTppoyRUIDMYl4YXdrFXeHnuUkK0rH8

{
  "key": "samarqand",
  "nameUz": "uz",
  "nameRu": "ru",
  "nameEn": "en"
}

###

GET http://localhost:8080/region/list
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4MTAzNjUsImV4cCI6MTY1NDgxMzk2NSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.QyusjigB5yLUR4XUc75esgkeBHfpG1EAKly2dLuSfnc


###

PUT http://localhost:8080/region/update/tashkent
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTQ4MTAzNjUsImV4cCI6MTY1NDgxMzk2NSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjozLCJyb2xlIjoiQURNSU4ifQ.QyusjigB5yLUR4XUc75esgkeBHfpG1EAKly2dLuSfnc

{
  "key": "ttt",
  "nameUz": "toshkent"
}